### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by qgolsteyn** [qgolsteyn/easyaspi#17]
**Description**

We need personas for our project. Let's come up with 2-3 personas each, for both teachers, parents, and students (or any other group you may think of).

**Dependencies**

**Acceptance criteria**

- [ ] 2-3 personas for each user group (student, teacher, etc.)

**Comment by no-or** [comment]
Student 1:
He is done with his textbook exercises and now want to practice more.

Student 2:
He finds textbooks boring. Wants to learn through app.

**Comment by armanzm** [comment]
Student 1: 
A lazy student who does not want to do his HW. His parents use this app and register as teachers to monitor the student's progress (e.g. no PS4 games until reached a certain level in the app) . 

Student 2: 
A person (not necessarily an elementary school student) who wants to practice his mental calculations skills (e.g. by multiplying 7 digit numbers).

**Comment by qgolsteyn** [comment]
Teacher 1:
