### ISSUE TITLE
Identify an approach for math expression visualization

### ISSUE THREAD

**Issue by qgolsteyn** [qgolsteyn/easyaspi#9]
**Description**

Identify a third party library or API that would allow us to display complex math expressions. We need to ensure that this approach is compatible with React Native and outputs scalable images.

**Dependencies**

This is somewhat dependent on #8 as the format of the math problem/solution will have an effect on how we can visualize them

**Acceptance criteria**

- [ ] Identify a good library or API for math expression visualization
- [ ] Demo the library or API

**Comment by armanzm** [comment]
I can take this issue if you are ok with that.

**Comment by qgolsteyn** [comment]
Sure!  Hmm,  so I was thinking about it in the context of our target audience, we might need to avoid Latex and go for something else. Because we are trying to make an app for grade 1 to 5, we probably should have something that looks a bit friendlier than Latex script.

**Comment by armanzm** [comment]
I'll try to find something that looks a little friendlier, but maybe there is still a way we can do it in latex (changing the font size or/and colour).

**Comment by qgolsteyn** [comment]
https://math.now.sh/
